import type { MymdTheme } from '../../../types'

export const academicLight: MymdTheme = {
  name: 'Academic Light',
  version: 1,
  colorMode: 'light',
  codeTheme: 'github-light',
  fonts: {
    body: 'Georgia, "Times New Roman", serif',
    heading: 'Georgia, "Times New Roman", serif',
    code: '"Courier New", Courier, monospace',
  },
  cssVariables: {
    '--mymd-bg': '#fefefe',
    '--mymd-text': '#222222',
    '--mymd-text-secondary': '#666666',
    '--mymd-heading': '#111111',
    '--mymd-link': '#1a0dab',
    '--mymd-link-hover': '#0000cc',
    '--mymd-border': '#cccccc',
    '--mymd-code-bg': '#f4f4f4',
    '--mymd-code-text': '#333333',
    '--mymd-blockquote-bg': '#f8f8f8',
    '--mymd-blockquote-border': '#767676',
    '--mymd-table-border': '#878787',
    '--mymd-table-stripe': '#f5f5f5',
    '--mymd-mark-bg': '#fef3a0',
    '--mymd-selection-bg': '#c8e6ff',
    '--mymd-sidebar-bg': '#f5f5f5',
    '--mymd-sidebar-text': '#222222',
    '--mymd-sidebar-active': '#1a0dab',
    '--mymd-sidebar-hover': '#e8e8e8',
    '--mymd-toolbar-bg': '#f5f5f5',
    '--mymd-toolbar-text': '#222222',
    '--mymd-toolbar-border': '#cccccc',
    '--mymd-shadow-sm': '0 1px 2px rgba(0,0,0,0.05)',
    '--mymd-shadow-md': '0 2px 6px rgba(0,0,0,0.08)',
    '--mymd-radius-sm': '2px',
    '--mymd-radius-md': '4px',
    '--mymd-content-padding': '3rem',
    '--mymd-alert-note-bg': '#e8eaf6',
    '--mymd-alert-note-border': '#3949ab',
    '--mymd-alert-tip-bg': '#e0f2f1',
    '--mymd-alert-tip-border': '#00796b',
    '--mymd-alert-warning-bg': '#fff3e0',
    '--mymd-alert-warning-border': '#c47200',
    '--mymd-alert-danger-bg': '#ffebee',
    '--mymd-alert-danger-border': '#b71c1c',
  },
}

export const academicDark: MymdTheme = {
  name: 'Academic Dark',
  version: 1,
  colorMode: 'dark',
  codeTheme: 'github-dark',
  fonts: {
    body: 'Georgia, "Times New Roman", serif',
    heading: 'Georgia, "Times New Roman", serif',
    code: '"Courier New", Courier, monospace',
  },
  cssVariables: {
    '--mymd-bg': '#1a1a2e',
    '--mymd-text': '#e0e0e0',
    '--mymd-text-secondary': '#9090a0',
    '--mymd-heading': '#f0f0f0',
    '--mymd-link': '#7986cb',
    '--mymd-link-hover': '#9fa8da',
    '--mymd-border': '#3a3a5c',
    '--mymd-code-bg': '#252540',
    '--mymd-code-text': '#e0e0e0',
    '--mymd-blockquote-bg': '#22223a',
    '--mymd-blockquote-border': '#6a6a96',
    '--mymd-table-border': '#64648a',
    '--mymd-table-stripe': '#22223a',
    '--mymd-mark-bg': '#3d3b00',
    '--mymd-selection-bg': '#2a3f6e',
    '--mymd-sidebar-bg': '#12122a',
    '--mymd-sidebar-text': '#e0e0e0',
    '--mymd-sidebar-active': '#7986cb',
    '--mymd-sidebar-hover': '#22223a',
    '--mymd-toolbar-bg': '#12122a',
    '--mymd-toolbar-text': '#e0e0e0',
    '--mymd-toolbar-border': '#3a3a5c',
    '--mymd-shadow-sm': '0 1px 2px rgba(0,0,0,0.4)',
    '--mymd-shadow-md': '0 2px 6px rgba(0,0,0,0.5)',
    '--mymd-radius-sm': '2px',
    '--mymd-radius-md': '4px',
    '--mymd-content-padding': '3rem',
    '--mymd-alert-note-bg': '#1a1f4a',
    '--mymd-alert-note-border': '#7986cb',
    '--mymd-alert-tip-bg': '#0d2926',
    '--mymd-alert-tip-border': '#4db6ac',
    '--mymd-alert-warning-bg': '#211a00',
    '--mymd-alert-warning-border': '#f59300',
    '--mymd-alert-danger-bg': '#200a14',
    '--mymd-alert-danger-border': '#ef5350',
  },
}
