import type { MymdTheme } from '../../../types'

export const cyberpunkLight: MymdTheme = {
  name: 'Cyberpunk Light',
  version: 1,
  colorMode: 'light',
  codeTheme: 'github-light',
  cssVariables: {
    '--mymd-bg': '#f8f9ff',
    '--mymd-text': '#0a0a1a',
    '--mymd-text-secondary': '#4a4a6a',
    '--mymd-heading': '#0a0a1a',
    '--mymd-link': '#0066ff',
    '--mymd-link-hover': '#0044cc',
    '--mymd-border': '#0066ff44',
    '--mymd-code-bg': '#e8eeff',
    '--mymd-code-text': '#0a0a1a',
    '--mymd-blockquote-bg': '#f0f4ff',
    '--mymd-blockquote-border': '#0066ff',
    '--mymd-table-border': '#0066ff33',
    '--mymd-table-stripe': '#f0f4ff',
    '--mymd-mark-bg': '#ff00ff22',
    '--mymd-selection-bg': '#0066ff33',
    '--mymd-sidebar-bg': '#eef0ff',
    '--mymd-sidebar-text': '#0a0a1a',
    '--mymd-sidebar-active': '#0066ff',
    '--mymd-sidebar-hover': '#e0e4ff',
    '--mymd-toolbar-bg': '#eef0ff',
    '--mymd-toolbar-text': '#0a0a1a',
    '--mymd-toolbar-border': '#0066ff33',
    '--mymd-shadow-sm': '0 1px 4px rgba(0,102,255,0.15)',
    '--mymd-shadow-md': '0 4px 16px rgba(0,102,255,0.2)',
    '--mymd-radius-sm': '2px',
    '--mymd-radius-md': '2px',
    '--mymd-content-padding': '2rem',
    '--mymd-alert-note-bg': '#e8f0ff',
    '--mymd-alert-note-border': '#0066ff',
    '--mymd-alert-tip-bg': '#e8fff0',
    '--mymd-alert-tip-border': '#00cc66',
    '--mymd-alert-warning-bg': '#fff8e0',
    '--mymd-alert-warning-border': '#ff9900',
    '--mymd-alert-danger-bg': '#ffe8ff',
    '--mymd-alert-danger-border': '#ff00ff',
  },
}

export const cyberpunkDark: MymdTheme = {
  name: 'Cyberpunk Dark',
  version: 1,
  colorMode: 'dark',
  codeTheme: 'one-dark-pro',
  cssVariables: {
    '--mymd-bg': '#0a0a0f',
    '--mymd-text': '#c8d8e8',
    '--mymd-text-secondary': '#5a7a8a',
    '--mymd-heading': '#00ffff',
    '--mymd-link': '#00ffff',
    '--mymd-link-hover': '#66ffff',
    '--mymd-border': '#00ffff22',
    '--mymd-code-bg': '#0f0f1a',
    '--mymd-code-text': '#00ff99',
    '--mymd-blockquote-bg': '#0a0f1a',
    '--mymd-blockquote-border': '#ff00ff',
    '--mymd-table-border': '#00ffff22',
    '--mymd-table-stripe': '#0f0f1a',
    '--mymd-mark-bg': '#ff00ff33',
    '--mymd-selection-bg': '#00ffff22',
    '--mymd-sidebar-bg': '#07070f',
    '--mymd-sidebar-text': '#c8d8e8',
    '--mymd-sidebar-active': '#00ffff',
    '--mymd-sidebar-hover': '#0f0f1a',
    '--mymd-toolbar-bg': '#07070f',
    '--mymd-toolbar-text': '#c8d8e8',
    '--mymd-toolbar-border': '#00ffff22',
    '--mymd-shadow-sm': '0 1px 4px rgba(0,255,255,0.15)',
    '--mymd-shadow-md': '0 0 20px rgba(0,255,255,0.2), 0 4px 12px rgba(0,0,0,0.5)',
    '--mymd-radius-sm': '2px',
    '--mymd-radius-md': '2px',
    '--mymd-content-padding': '2rem',
    '--mymd-alert-note-bg': '#001a2a',
    '--mymd-alert-note-border': '#00ffff',
    '--mymd-alert-tip-bg': '#001a10',
    '--mymd-alert-tip-border': '#00ff99',
    '--mymd-alert-warning-bg': '#1a1000',
    '--mymd-alert-warning-border': '#ffaa00',
    '--mymd-alert-danger-bg': '#1a0020',
    '--mymd-alert-danger-border': '#ff00ff',
  },
}
