import type { MymdTheme } from '../../../types'

export const githubLight: MymdTheme = {
  name: 'GitHub Light',
  version: 1,
  colorMode: 'light',
  codeTheme: 'github-light',
  cssVariables: {
    '--mymd-bg': '#ffffff',
    '--mymd-text': '#1f2328',
    '--mymd-text-secondary': '#656d76',
    '--mymd-heading': '#1f2328',
    '--mymd-link': '#0969da',
    '--mymd-link-hover': '#0550ae',
    '--mymd-border': '#d0d7de',
    '--mymd-code-bg': '#f6f8fa',
    '--mymd-code-text': '#1f2328',
    '--mymd-blockquote-bg': 'transparent',
    '--mymd-blockquote-border': '#d0d7de',
    '--mymd-table-border': '#d0d7de',
    '--mymd-table-stripe': '#f6f8fa',
    '--mymd-mark-bg': '#fff8c5',
    '--mymd-selection-bg': '#b6e3ff',
    '--mymd-sidebar-bg': '#f6f8fa',
    '--mymd-sidebar-text': '#1f2328',
    '--mymd-sidebar-active': '#0969da',
    '--mymd-sidebar-hover': '#eaeef2',
    '--mymd-toolbar-bg': '#f6f8fa',
    '--mymd-toolbar-text': '#1f2328',
    '--mymd-toolbar-border': '#d0d7de',
    '--mymd-shadow-sm': '0 1px 2px rgba(0,0,0,0.06)',
    '--mymd-shadow-md': '0 4px 12px rgba(0,0,0,0.08)',
    '--mymd-radius-sm': '4px',
    '--mymd-radius-md': '8px',
    '--mymd-content-padding': '2rem',
    '--mymd-alert-note-bg': '#ddf4ff',
    '--mymd-alert-note-border': '#54aeff',
    '--mymd-alert-tip-bg': '#dafbe1',
    '--mymd-alert-tip-border': '#4ac26b',
    '--mymd-alert-warning-bg': '#fff8c5',
    '--mymd-alert-warning-border': '#d4a72c',
    '--mymd-alert-danger-bg': '#ffebe9',
    '--mymd-alert-danger-border': '#ff8182',
  },
}

export const githubDark: MymdTheme = {
  name: 'GitHub Dark',
  version: 1,
  colorMode: 'dark',
  codeTheme: 'github-dark',
  cssVariables: {
    '--mymd-bg': '#0d1117',
    '--mymd-text': '#e6edf3',
    '--mymd-text-secondary': '#8b949e',
    '--mymd-heading': '#e6edf3',
    '--mymd-link': '#58a6ff',
    '--mymd-link-hover': '#79c0ff',
    '--mymd-border': '#30363d',
    '--mymd-code-bg': '#161b22',
    '--mymd-code-text': '#e6edf3',
    '--mymd-blockquote-bg': 'transparent',
    '--mymd-blockquote-border': '#30363d',
    '--mymd-table-border': '#30363d',
    '--mymd-table-stripe': '#161b22',
    '--mymd-mark-bg': '#bb800966',
    '--mymd-selection-bg': '#264f78',
    '--mymd-sidebar-bg': '#010409',
    '--mymd-sidebar-text': '#e6edf3',
    '--mymd-sidebar-active': '#58a6ff',
    '--mymd-sidebar-hover': '#161b22',
    '--mymd-toolbar-bg': '#010409',
    '--mymd-toolbar-text': '#e6edf3',
    '--mymd-toolbar-border': '#30363d',
    '--mymd-shadow-sm': '0 1px 2px rgba(0,0,0,0.3)',
    '--mymd-shadow-md': '0 4px 12px rgba(0,0,0,0.4)',
    '--mymd-radius-sm': '4px',
    '--mymd-radius-md': '8px',
    '--mymd-content-padding': '2rem',
    '--mymd-alert-note-bg': '#0d1d30',
    '--mymd-alert-note-border': '#1f6feb',
    '--mymd-alert-tip-bg': '#0d2818',
    '--mymd-alert-tip-border': '#238636',
    '--mymd-alert-warning-bg': '#2a1f04',
    '--mymd-alert-warning-border': '#9e6a03',
    '--mymd-alert-danger-bg': '#2d0e0e',
    '--mymd-alert-danger-border': '#da3633',
  },
}
