import type { MymdTheme } from '../../../types'

export const minimalLight: MymdTheme = {
  name: 'Minimal Light',
  version: 1,
  colorMode: 'light',
  codeTheme: 'github-light',
  cssVariables: {
    '--mymd-bg': '#ffffff',
    '--mymd-text': '#000000',
    '--mymd-text-secondary': '#555555',
    '--mymd-heading': '#000000',
    '--mymd-link': '#000000',
    '--mymd-link-hover': '#444444',
    '--mymd-border': '#949494',
    '--mymd-code-bg': '#f8f8f8',
    '--mymd-code-text': '#333333',
    '--mymd-blockquote-bg': 'transparent',
    '--mymd-blockquote-border': '#767676',
    '--mymd-table-border': '#949494',
    '--mymd-table-stripe': '#f8f8f8',
    '--mymd-mark-bg': '#ffffaa',
    '--mymd-selection-bg': '#b0d4ff',
    '--mymd-sidebar-bg': '#fafafa',
    '--mymd-sidebar-text': '#000000',
    '--mymd-sidebar-active': '#000000',
    '--mymd-sidebar-hover': '#eeeeee',
    '--mymd-toolbar-bg': '#fafafa',
    '--mymd-toolbar-text': '#000000',
    '--mymd-toolbar-border': '#909090',
    '--mymd-shadow-sm': 'none',
    '--mymd-shadow-md': '0 1px 4px rgba(0,0,0,0.08)',
    '--mymd-radius-sm': '2px',
    '--mymd-radius-md': '4px',
    '--mymd-content-padding': '2rem',
    '--mymd-alert-note-bg': '#f4f6ff',
    '--mymd-alert-note-border': '#6a6a9e',
    '--mymd-alert-tip-bg': '#f4fff6',
    '--mymd-alert-tip-border': '#6a8a6a',
    '--mymd-alert-warning-bg': '#fffcf2',
    '--mymd-alert-warning-border': '#8a7a1e',
    '--mymd-alert-danger-bg': '#fff4f4',
    '--mymd-alert-danger-border': '#907070',
  },
}

export const minimalDark: MymdTheme = {
  name: 'Minimal Dark',
  version: 1,
  colorMode: 'dark',
  codeTheme: 'github-dark',
  cssVariables: {
    '--mymd-bg': '#111111',
    '--mymd-text': '#eeeeee',
    '--mymd-text-secondary': '#888888',
    '--mymd-heading': '#ffffff',
    '--mymd-link': '#cccccc',
    '--mymd-link-hover': '#ffffff',
    '--mymd-border': '#626262',
    '--mymd-code-bg': '#222222',
    '--mymd-code-text': '#dddddd',
    '--mymd-blockquote-bg': 'transparent',
    '--mymd-blockquote-border': '#6e6e6e',
    '--mymd-table-border': '#626262',
    '--mymd-table-stripe': '#1a1a1a',
    '--mymd-mark-bg': '#444400',
    '--mymd-selection-bg': '#2a3f60',
    '--mymd-sidebar-bg': '#0a0a0a',
    '--mymd-sidebar-text': '#eeeeee',
    '--mymd-sidebar-active': '#ffffff',
    '--mymd-sidebar-hover': '#222222',
    '--mymd-toolbar-bg': '#0a0a0a',
    '--mymd-toolbar-text': '#eeeeee',
    '--mymd-toolbar-border': '#626262',
    '--mymd-shadow-sm': 'none',
    '--mymd-shadow-md': '0 1px 4px rgba(0,0,0,0.5)',
    '--mymd-radius-sm': '2px',
    '--mymd-radius-md': '4px',
    '--mymd-content-padding': '2rem',
    '--mymd-alert-note-bg': '#191926',
    '--mymd-alert-note-border': '#7777aa',
    '--mymd-alert-tip-bg': '#1a2e1a',
    '--mymd-alert-tip-border': '#779977',
    '--mymd-alert-warning-bg': '#2a2408',
    '--mymd-alert-warning-border': '#998820',
    '--mymd-alert-danger-bg': '#2a1818',
    '--mymd-alert-danger-border': '#997777',
  },
}
