import type { MymdTheme } from '../../../types'

export const minimalLight: MymdTheme = {
  name: 'Minimal Light',
  version: 1,
  colorMode: 'light',
  codeTheme: 'github-light',
  cssVariables: {
    '--mymd-bg': '#ffffff',
    '--mymd-text': '#000000',
    '--mymd-text-secondary': '#555555',
    '--mymd-heading': '#000000',
    '--mymd-link': '#000000',
    '--mymd-link-hover': '#444444',
    '--mymd-border': '#dddddd',
    '--mymd-code-bg': '#f8f8f8',
    '--mymd-code-text': '#333333',
    '--mymd-blockquote-bg': 'transparent',
    '--mymd-blockquote-border': '#aaaaaa',
    '--mymd-table-border': '#cccccc',
    '--mymd-table-stripe': '#f8f8f8',
    '--mymd-mark-bg': '#ffffaa',
    '--mymd-selection-bg': '#b0d4ff',
    '--mymd-sidebar-bg': '#fafafa',
    '--mymd-sidebar-text': '#000000',
    '--mymd-sidebar-active': '#000000',
    '--mymd-sidebar-hover': '#eeeeee',
    '--mymd-toolbar-bg': '#fafafa',
    '--mymd-toolbar-text': '#000000',
    '--mymd-toolbar-border': '#dddddd',
    '--mymd-shadow-sm': 'none',
    '--mymd-shadow-md': '0 1px 4px rgba(0,0,0,0.08)',
    '--mymd-radius-sm': '2px',
    '--mymd-radius-md': '4px',
    '--mymd-content-padding': '2rem',
    '--mymd-alert-note-bg': '#f0f4ff',
    '--mymd-alert-note-border': '#8888cc',
    '--mymd-alert-tip-bg': '#f0fff4',
    '--mymd-alert-tip-border': '#88aa88',
    '--mymd-alert-warning-bg': '#fffbf0',
    '--mymd-alert-warning-border': '#ccaa44',
    '--mymd-alert-danger-bg': '#fff0f0',
    '--mymd-alert-danger-border': '#cc8888',
  },
}

export const minimalDark: MymdTheme = {
  name: 'Minimal Dark',
  version: 1,
  colorMode: 'dark',
  codeTheme: 'github-dark',
  cssVariables: {
    '--mymd-bg': '#111111',
    '--mymd-text': '#eeeeee',
    '--mymd-text-secondary': '#888888',
    '--mymd-heading': '#ffffff',
    '--mymd-link': '#cccccc',
    '--mymd-link-hover': '#ffffff',
    '--mymd-border': '#333333',
    '--mymd-code-bg': '#222222',
    '--mymd-code-text': '#dddddd',
    '--mymd-blockquote-bg': 'transparent',
    '--mymd-blockquote-border': '#555555',
    '--mymd-table-border': '#333333',
    '--mymd-table-stripe': '#1a1a1a',
    '--mymd-mark-bg': '#444400',
    '--mymd-selection-bg': '#2a3f60',
    '--mymd-sidebar-bg': '#0a0a0a',
    '--mymd-sidebar-text': '#eeeeee',
    '--mymd-sidebar-active': '#ffffff',
    '--mymd-sidebar-hover': '#222222',
    '--mymd-toolbar-bg': '#0a0a0a',
    '--mymd-toolbar-text': '#eeeeee',
    '--mymd-toolbar-border': '#333333',
    '--mymd-shadow-sm': 'none',
    '--mymd-shadow-md': '0 1px 4px rgba(0,0,0,0.5)',
    '--mymd-radius-sm': '2px',
    '--mymd-radius-md': '4px',
    '--mymd-content-padding': '2rem',
    '--mymd-alert-note-bg': '#1a1a33',
    '--mymd-alert-note-border': '#6666aa',
    '--mymd-alert-tip-bg': '#1a331a',
    '--mymd-alert-tip-border': '#66aa66',
    '--mymd-alert-warning-bg': '#33280a',
    '--mymd-alert-warning-border': '#aa8822',
    '--mymd-alert-danger-bg': '#331a1a',
    '--mymd-alert-danger-border': '#aa6666',
  },
}
