import type { MymdTheme } from '../../../types'

export const readerLight: MymdTheme = {
  name: 'Reader Light',
  version: 1,
  colorMode: 'light',
  codeTheme: 'github-light',
  fonts: {
    body: '"Palatino Linotype", Palatino, "Book Antiqua", serif',
    heading: '"Palatino Linotype", Palatino, "Book Antiqua", serif',
    code: '"Fira Code", "Fira Mono", monospace',
  },
  cssVariables: {
    '--mymd-bg': '#f5f0e8',
    '--mymd-text': '#3b3228',
    '--mymd-text-secondary': '#7a6e64',
    '--mymd-heading': '#2c2419',
    '--mymd-link': '#8b5e3c',
    '--mymd-link-hover': '#6b3e1c',
    '--mymd-border': '#d5c8b8',
    '--mymd-code-bg': '#ede8e0',
    '--mymd-code-text': '#5c3d2e',
    '--mymd-blockquote-bg': '#ede8e0',
    '--mymd-blockquote-border': '#c4a882',
    '--mymd-table-border': '#c4b8a4',
    '--mymd-table-stripe': '#ede8e0',
    '--mymd-mark-bg': '#f9e4a0',
    '--mymd-selection-bg': '#d4b896',
    '--mymd-sidebar-bg': '#ede8e0',
    '--mymd-sidebar-text': '#3b3228',
    '--mymd-sidebar-active': '#8b5e3c',
    '--mymd-sidebar-hover': '#ddd5c8',
    '--mymd-toolbar-bg': '#ede8e0',
    '--mymd-toolbar-text': '#3b3228',
    '--mymd-toolbar-border': '#d5c8b8',
    '--mymd-shadow-sm': '0 1px 2px rgba(59,50,40,0.08)',
    '--mymd-shadow-md': '0 3px 8px rgba(59,50,40,0.12)',
    '--mymd-radius-sm': '3px',
    '--mymd-radius-md': '6px',
    '--mymd-content-padding': '2.5rem',
    '--mymd-alert-note-bg': '#e8eef8',
    '--mymd-alert-note-border': '#7b9ed4',
    '--mymd-alert-tip-bg': '#e6f4ea',
    '--mymd-alert-tip-border': '#72b87a',
    '--mymd-alert-warning-bg': '#fef8e7',
    '--mymd-alert-warning-border': '#e8b84b',
    '--mymd-alert-danger-bg': '#fcecea',
    '--mymd-alert-danger-border': '#d9736b',
  },
}

export const readerDark: MymdTheme = {
  name: 'Reader Dark',
  version: 1,
  colorMode: 'dark',
  codeTheme: 'github-dark',
  fonts: {
    body: '"Palatino Linotype", Palatino, "Book Antiqua", serif',
    heading: '"Palatino Linotype", Palatino, "Book Antiqua", serif',
    code: '"Fira Code", "Fira Mono", monospace',
  },
  cssVariables: {
    '--mymd-bg': '#1c1a17',
    '--mymd-text': '#c8b99a',
    '--mymd-text-secondary': '#8a7a65',
    '--mymd-heading': '#d9c9aa',
    '--mymd-link': '#c4956a',
    '--mymd-link-hover': '#d4a57a',
    '--mymd-border': '#3a3020',
    '--mymd-code-bg': '#252218',
    '--mymd-code-text': '#c8b99a',
    '--mymd-blockquote-bg': '#252218',
    '--mymd-blockquote-border': '#5a4a30',
    '--mymd-table-border': '#3a3020',
    '--mymd-table-stripe': '#252218',
    '--mymd-mark-bg': '#4a3800',
    '--mymd-selection-bg': '#5a3a20',
    '--mymd-sidebar-bg': '#141210',
    '--mymd-sidebar-text': '#c8b99a',
    '--mymd-sidebar-active': '#c4956a',
    '--mymd-sidebar-hover': '#252218',
    '--mymd-toolbar-bg': '#141210',
    '--mymd-toolbar-text': '#c8b99a',
    '--mymd-toolbar-border': '#3a3020',
    '--mymd-shadow-sm': '0 1px 2px rgba(0,0,0,0.4)',
    '--mymd-shadow-md': '0 3px 8px rgba(0,0,0,0.5)',
    '--mymd-radius-sm': '3px',
    '--mymd-radius-md': '6px',
    '--mymd-content-padding': '2.5rem',
    '--mymd-alert-note-bg': '#1a2030',
    '--mymd-alert-note-border': '#5070a0',
    '--mymd-alert-tip-bg': '#122018',
    '--mymd-alert-tip-border': '#408050',
    '--mymd-alert-warning-bg': '#281e08',
    '--mymd-alert-warning-border': '#a07830',
    '--mymd-alert-danger-bg': '#281010',
    '--mymd-alert-danger-border': '#904040',
  },
}
