import type { MymdTheme } from '../../../types'

export const retroLight: MymdTheme = {
  name: 'Retro Light',
  version: 1,
  colorMode: 'light',
  codeTheme: 'vitesse-light',
  cssVariables: {
    '--mymd-bg': '#fdf6e3',
    '--mymd-text': '#2d2006',
    '--mymd-text-secondary': '#7a6030',
    '--mymd-heading': '#1a1200',
    '--mymd-link': '#b45309',
    '--mymd-link-hover': '#92400e',
    '--mymd-border': '#9a7a28',
    '--mymd-code-bg': '#ede8d8',
    '--mymd-code-text': '#2d2006',
    '--mymd-blockquote-bg': '#f5edd8',
    '--mymd-blockquote-border': '#9a7a28',
    '--mymd-table-border': '#9a7a28',
    '--mymd-table-stripe': '#f0e8d0',
    '--mymd-mark-bg': '#fbbf24',
    '--mymd-selection-bg': '#fcd34d',
    '--mymd-sidebar-bg': '#f0e8d0',
    '--mymd-sidebar-text': '#2d2006',
    '--mymd-sidebar-active': '#b45309',
    '--mymd-sidebar-hover': '#e8ddc0',
    '--mymd-toolbar-bg': '#f0e8d0',
    '--mymd-toolbar-text': '#2d2006',
    '--mymd-toolbar-border': '#9a7a28',
    '--mymd-shadow-sm': 'none',
    '--mymd-shadow-md': 'none',
    '--mymd-radius-sm': '0px',
    '--mymd-radius-md': '0px',
    '--mymd-content-padding': '2rem',
    '--mymd-alert-note-bg': '#e8f0e8',
    '--mymd-alert-note-border': '#5a8a5a',
    '--mymd-alert-tip-bg': '#e0f0d8',
    '--mymd-alert-tip-border': '#5a8a5a',
    '--mymd-alert-warning-bg': '#fff0d0',
    '--mymd-alert-warning-border': '#9a7a28',
    '--mymd-alert-danger-bg': '#f8e8e0',
    '--mymd-alert-danger-border': '#aa5544',
  },
}

export const retroDark: MymdTheme = {
  name: 'Retro Dark',
  version: 1,
  colorMode: 'dark',
  codeTheme: 'nord',
  cssVariables: {
    '--mymd-bg': '#0f380f',
    '--mymd-text': '#9bbc0f',
    '--mymd-text-secondary': '#85a520',
    '--mymd-heading': '#b8d418',
    '--mymd-link': '#c8e820',
    '--mymd-link-hover': '#e0ff30',
    '--mymd-border': '#4a8a4a',
    '--mymd-code-bg': '#0a2a0a',
    '--mymd-code-text': '#9bbc0f',
    '--mymd-blockquote-bg': '#0a2a0a',
    '--mymd-blockquote-border': '#4a8a4a',
    '--mymd-table-border': '#4a8a4a',
    '--mymd-table-stripe': '#0a2a0a',
    '--mymd-mark-bg': '#2a5a00',
    '--mymd-selection-bg': '#1a4a00',
    '--mymd-sidebar-bg': '#080f08',
    '--mymd-sidebar-text': '#9bbc0f',
    '--mymd-sidebar-active': '#c8e820',
    '--mymd-sidebar-hover': '#0a2a0a',
    '--mymd-toolbar-bg': '#080f08',
    '--mymd-toolbar-text': '#9bbc0f',
    '--mymd-toolbar-border': '#4a8a4a',
    '--mymd-shadow-sm': 'none',
    '--mymd-shadow-md': 'none',
    '--mymd-radius-sm': '0px',
    '--mymd-radius-md': '0px',
    '--mymd-content-padding': '2rem',
    '--mymd-alert-note-bg': '#0a1a0a',
    '--mymd-alert-note-border': '#4a8a4a',
    '--mymd-alert-tip-bg': '#0a200a',
    '--mymd-alert-tip-border': '#5a9a5a',
    '--mymd-alert-warning-bg': '#1a1500',
    '--mymd-alert-warning-border': '#8a7a00',
    '--mymd-alert-danger-bg': '#1a0a0a',
    '--mymd-alert-danger-border': '#aa4444',
  },
}
