import type { MymdTheme } from '../../../types'

export const typoraLight: MymdTheme = {
  name: 'Typora Light',
  version: 1,
  colorMode: 'light',
  codeTheme: 'github-light',
  cssVariables: {
    '--mymd-bg': '#ffffff',
    '--mymd-text': '#333333',
    '--mymd-text-secondary': '#777777',
    '--mymd-heading': '#111111',
    '--mymd-link': '#428bca',
    '--mymd-link-hover': '#2a6496',
    '--mymd-border': '#e0e0e0',
    '--mymd-code-bg': '#f5f5f5',
    '--mymd-code-text': '#c7254e',
    '--mymd-blockquote-bg': '#f9f9f9',
    '--mymd-blockquote-border': '#cccccc',
    '--mymd-table-border': '#dddddd',
    '--mymd-table-stripe': '#f9f9f9',
    '--mymd-mark-bg': '#fff9c4',
    '--mymd-selection-bg': '#b3d7ff',
    '--mymd-sidebar-bg': '#f7f7f7',
    '--mymd-sidebar-text': '#333333',
    '--mymd-sidebar-active': '#428bca',
    '--mymd-sidebar-hover': '#eeeeee',
    '--mymd-toolbar-bg': '#f7f7f7',
    '--mymd-toolbar-text': '#333333',
    '--mymd-toolbar-border': '#e0e0e0',
    '--mymd-shadow-sm': '0 1px 3px rgba(0,0,0,0.08)',
    '--mymd-shadow-md': '0 2px 8px rgba(0,0,0,0.10)',
    '--mymd-radius-sm': '3px',
    '--mymd-radius-md': '6px',
    '--mymd-content-padding': '2rem',
    '--mymd-alert-note-bg': '#e7f3fe',
    '--mymd-alert-note-border': '#2196f3',
    '--mymd-alert-tip-bg': '#e8f5e9',
    '--mymd-alert-tip-border': '#4caf50',
    '--mymd-alert-warning-bg': '#fffde7',
    '--mymd-alert-warning-border': '#ffc107',
    '--mymd-alert-danger-bg': '#fce4ec',
    '--mymd-alert-danger-border': '#e91e63',
  },
}

export const typoraDark: MymdTheme = {
  name: 'Typora Dark',
  version: 1,
  colorMode: 'dark',
  codeTheme: 'github-dark',
  cssVariables: {
    '--mymd-bg': '#1e1e1e',
    '--mymd-text': '#d4d4d4',
    '--mymd-text-secondary': '#888888',
    '--mymd-heading': '#e8e8e8',
    '--mymd-link': '#569cd6',
    '--mymd-link-hover': '#79b8ff',
    '--mymd-border': '#3c3c3c',
    '--mymd-code-bg': '#2d2d2d',
    '--mymd-code-text': '#ce9178',
    '--mymd-blockquote-bg': '#252525',
    '--mymd-blockquote-border': '#555555',
    '--mymd-table-border': '#3c3c3c',
    '--mymd-table-stripe': '#252525',
    '--mymd-mark-bg': '#4a3f00',
    '--mymd-selection-bg': '#264f78',
    '--mymd-sidebar-bg': '#181818',
    '--mymd-sidebar-text': '#d4d4d4',
    '--mymd-sidebar-active': '#569cd6',
    '--mymd-sidebar-hover': '#2a2a2a',
    '--mymd-toolbar-bg': '#181818',
    '--mymd-toolbar-text': '#d4d4d4',
    '--mymd-toolbar-border': '#3c3c3c',
    '--mymd-shadow-sm': '0 1px 3px rgba(0,0,0,0.4)',
    '--mymd-shadow-md': '0 2px 8px rgba(0,0,0,0.5)',
    '--mymd-radius-sm': '3px',
    '--mymd-radius-md': '6px',
    '--mymd-content-padding': '2rem',
    '--mymd-alert-note-bg': '#1a2733',
    '--mymd-alert-note-border': '#569cd6',
    '--mymd-alert-tip-bg': '#1a2b1a',
    '--mymd-alert-tip-border': '#4ec950',
    '--mymd-alert-warning-bg': '#2b2500',
    '--mymd-alert-warning-border': '#ffd700',
    '--mymd-alert-danger-bg': '#2b1a1f',
    '--mymd-alert-danger-border': '#f48771',
  },
}
